/**
 * One-time cleanup of LIVE listings against the rules the gate now applies to
 * new ones (27 Sep 2026): no way in → archived; the same gathering listed
 * twice → the extra copies archived; published without a moderation verdict →
 * moderated now, or held (back to pending) if moderation still can't run.
 *
 * Prints a migration (explicit ids, reversible by the markers it writes) to
 * stdout. It does not write to the database itself.
 *
 *   npx tsx --env-file=.env.local scripts/audit/walk-cleanup.ts > supabase/migrations/<ts>_walk_cleanup.sql
 *   npx tsx --env-file=.env.local scripts/audit/walk-cleanup.ts --no-moderation   # skip Gemini calls
 */
import { createAdminClient } from "@/lib/supabase/admin";
import { nowInBali } from "@/lib/events/bali-time";
import { wayIn, sameGathering, type SlotFields } from "@/lib/events/listing-checks";
import { moderateEvent } from "@/lib/events/moderation";
import { parseRecurrenceRule } from "@/lib/recurrence";

type Row = SlotFields & {
  description: string | null;
  short_description: string | null;
  organizer_name: string | null;
  source_url: string | null;
  external_ticket_url: string | null;
  organizer_contact: string | null;
  organizer_instagram: string | null;
  moderation_reason: string | null;
  created_at: string;
};

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

async function main() {
  const skipModeration = process.argv.includes("--no-moderation");
  const supabase = createAdminClient();
  const today = nowInBali().dateStr;
  const { data, error } = await supabase
    .from("events")
    .select("id,title,description,short_description,venue_name,start_date,end_date,start_time,is_recurring,recurrence_rule,organizer_name,source_url,external_ticket_url,organizer_contact,organizer_instagram,moderation_reason,created_at")
    .eq("status", "approved")
    .or(`start_date.gte.${today},is_recurring.eq.true,end_date.gte.${today}`);
  if (error) throw error;
  const rows = ((data ?? []) as Row[]).filter((r) => {
    // Same liveness test the feed uses: a series whose `until` has passed shows nothing.
    const until = r.is_recurring ? parseRecurrenceRule(r.recurrence_rule)?.until : null;
    return !until || until >= today;
  });

  const noWayIn = rows.filter((r) => !wayIn(r));
  const withWay = rows.filter((r) => wayIn(r));

  // Keepers first: series before one-offs (a one-off never displaces a series),
  // then the surest way in, then moderated, then oldest.
  const strength = (r: Row) => ({ tickets: 2, organiser: 1, "walk-in": 0 })[wayIn(r)!.kind];
  const ordered = [...withWay].sort(
    (a, b) =>
      Number(!!b.is_recurring) - Number(!!a.is_recurring) ||
      strength(b) - strength(a) ||
      Number(b.moderation_reason !== "auto_gate:unmoderated") - Number(a.moderation_reason !== "auto_gate:unmoderated") ||
      a.created_at.localeCompare(b.created_at),
  );
  const kept: Row[] = [];
  const dups: { row: Row; of: Row }[] = [];
  for (const r of ordered) {
    const twin = kept.find((k) => sameGathering(r, k) && !(r.is_recurring && !k.is_recurring));
    if (twin) dups.push({ row: r, of: twin });
    else kept.push(r);
  }

  const unmoderated = kept.filter((r) => r.moderation_reason === "auto_gate:unmoderated");
  const passed: Row[] = [];
  const flagged: { row: Row; reason: string }[] = [];
  const held: Row[] = [];
  for (const r of unmoderated) {
    if (skipModeration) { held.push(r); continue; }
    const v = await moderateEvent({
      title: r.title,
      description: r.description || r.short_description || r.title,
      organizer_name: r.organizer_name,
      venue_name: r.venue_name,
      source_url: r.source_url,
      origin: "ingestion",
    });
    if (!v.ok) flagged.push({ row: r, reason: `${v.flag}: ${v.reason}` });
    else if (v.notes === "moderation_failed_open") held.push(r);
    else passed.push(r);
    await new Promise((res) => setTimeout(res, 700));
  }

  const ids = (list: Row[]) => list.map((r) => `  ${q(r.id)}, -- ${r.title.slice(0, 60).replace(/\n/g, " ")} @ ${r.venue_name ?? "?"}`).join("\n").replace(/,( -- [^\n]*)$/, "$1");
  const out: string[] = [];
  out.push(`-- Walk cleanup, ${today} (Bali). Generated by scripts/audit/walk-cleanup.ts.`);
  out.push(`-- Live listings: ${rows.length}. No way in: ${noWayIn.length}. Duplicate copies: ${dups.length}.`);
  out.push(`-- Published unmoderated: ${unmoderated.length} -> moderated ok ${passed.length}, flagged ${flagged.length}, still unmoderatable (held) ${held.length}.`);
  out.push(`-- Reverse any group by its marker: UPDATE events SET status='approved', moderation_reason=<old> WHERE moderation_reason='<marker>'.`);
  out.push("");
  if (noWayIn.length) {
    out.push(`-- 1. No ticket link, no organiser contact, no named venue (${noWayIn.length}).`);
    out.push(`UPDATE events SET status = 'archived', moderation_reason = 'walk_2026_09_27:no_way_in'\nWHERE status = 'approved' AND id IN (\n${ids(noWayIn)}\n);`);
    out.push("");
  }
  for (const d of dups) {
    out.push(`-- dup: ${d.row.title.slice(0, 50)} (${d.row.start_time}) = ${d.of.title.slice(0, 50)}`);
    out.push(`UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:${d.of.id}' WHERE status = 'approved' AND id = ${q(d.row.id)};`);
  }
  if (dups.length) out.push("");
  if (passed.length) {
    out.push(`-- 3a. Moderated now, cleared (${passed.length}).`);
    out.push(`UPDATE events SET moderation_reason = 'auto_gate:moderated_late' WHERE moderation_reason = 'auto_gate:unmoderated' AND id IN (\n${ids(passed)}\n);`);
    out.push("");
  }
  for (const f of flagged) {
    out.push(`-- flagged: ${f.reason.slice(0, 120).replace(/\n/g, " ")}`);
    out.push(`UPDATE events SET status = 'rejected', moderation_reason = 'walk_2026_09_27:flagged', rejection_reason = ${q(f.reason)} WHERE status = 'approved' AND id = ${q(f.row.id)};`);
  }
  if (held.length) {
    out.push(`-- 3c. Moderation still can't run: back to pending for the nightly gate (${held.length}).`);
    out.push(`UPDATE events SET status = 'pending', auto_approved_at = NULL, moderation_reason = 'walk_2026_09_27:held_unmoderated' WHERE status = 'approved' AND id IN (\n${ids(held)}\n);`);
  }
  console.log(out.join("\n"));
}
main().catch((e) => { console.error(e); process.exit(1); });
