-- OPTIONAL since the evening of 2026-09-27: public pages now apply these rules
-- at read time (visibleListings in src/lib/events/listing-checks.ts), so this
-- only tidies the rows themselves.
-- STATUS: written 2026-09-27, NOT applied by the agent that wrote it (the
-- auto-mode classifier blocks bulk production writes). Ben applies it with:
--   npx tsx --env-file=.env.local scripts/apply-migration.ts supabase/migrations/20260927120000_walk_cleanup.sql
-- Every statement is guarded by `status = 'approved'`, so rows that changed
-- since are skipped. Regenerate with scripts/audit/walk-cleanup.ts if it is
-- more than a few days old.
-- Walk cleanup, 2026-09-27 (Bali). Generated by scripts/audit/walk-cleanup.ts.
-- Live listings: 209. No way in: 34. Duplicate copies: 17.
-- Published unmoderated: 27 -> moderated ok 0, flagged 0, still unmoderatable (held) 27.
-- Reverse any group by its marker: UPDATE events SET status='approved', moderation_reason=<old> WHERE moderation_reason='<marker>'.

-- 1. No ticket link, no organiser contact, no named venue (34).
UPDATE events SET status = 'archived', moderation_reason = 'walk_2026_09_27:no_way_in'
WHERE status = 'approved' AND id IN (
  '76167a71-9e76-4a9a-9d69-3835bf3f9bd8', -- Solo Improvisation w/ Nastya @ ?
  '11752acf-6578-42c8-b602-22ccc2aa1954', -- Somatic Breathwork: Let Body Speak w/ Wei Wei @ Ubud
  'e2ebc424-e3e8-4b00-8f50-7c856da1be0e', -- Holotropic Breathwork: Explore Inner Depth w/ Wei Wei @ Ubud
  '89a93057-5ccf-47fe-b37a-1e558e7ff284', -- Rebirthing Breathwork: Return to Innate Wholeness w/ Wei Wei @ Ubud
  'aabf11db-5af5-4624-9a5e-921f19d72a15', -- Soul Temple Touch w/ Miracle @ Penestanan
  '880ede32-9bd9-4fa3-a51e-27edf1a77d88', -- Contact Improvisation Class for Beginners w/ Seamless @ Penestanan
  'fa45c3e1-ac22-4802-8ca7-0ac4cb708ab5', -- Contact Improvisation & Partnering w/ Seamless @ Penestanan
  '4bce5585-ecad-4885-b20e-a3eac50627bc', -- The Art of Dance Alchemy: Embodied Movement Practice w/ Gora @ Penestanan
  '0662f0f7-651b-4393-b7ac-caa48a8215aa', -- Dancing The Archetypes w/ Trisha @ Sayan
  'ef542041-6fd5-4f20-b248-2804f047f7a6', -- The Sanctuary of You @ Penestanan
  '73888256-d0d4-4e92-88ba-bb6ed6b556da', -- Voices of The Drum w/ Sirvan 2 Handpans shop @ Ubud
  '38e70188-240a-4e3f-af19-e5b14e64c536', -- Voices of The Ancient Sea w/ When drummers were women @ Mas
  '579fa9ab-1862-4a4d-9869-d560d44a073c', -- The Eros & Spyche Method @ Penestanan
  'c2f2e099-6dcf-486f-b7a7-218f85794a47', -- Womb & Voice Awakening w/ Aika Rose 🌹 @ Ubud
  '99a5177c-bd86-4c17-a3c6-f424dc62fd5a', -- Contact Improvisation & Partnering Class w/ Seamless @ Penestanan
  '9ccfe9c7-0f47-4577-a7d3-167392935b77', -- Saturday Contact Improvisation Jam w/ Seamless @ Penestanan
  '5e43eeb2-90da-43c8-97e1-9d4b61eedd9c', -- Women's Group Voice Activation Class w/ Donnasheva Artist. V @ Ubud
  '54ec5a9e-e7ea-478d-9c6e-02c30d306e12', -- Moving with The Voices Within-Private Archetype and Embodime @ Central Ubud
  'c93bbb5c-8131-4051-ba88-1be3afe4dcc2', -- Tantric Evolution @ Ubud
  '4c1f85d9-e1a2-4cb1-926a-0247cd64e171', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  '1d3a3177-8c10-46b6-b73d-1251d39c4ee0', -- The Embodied Voice: An Intimate Vocal Practice for Women w/  @ Ubud
  '115b573d-c567-4f6f-b6b2-6b602c2b2b16', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  '187a78b3-d055-4bfc-b649-9bd39c54ae8e', -- Thai Massage Jam @ ?
  '1f410c0d-b694-49f8-9590-7fa5fc421553', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  '29542641-b58b-4282-8930-15656f3178d2', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  '74317c59-b433-4365-a929-368cbb25d9d8', -- The Living Heart @ Kedewatan
  'b83ea8c2-2e3e-4f3a-8232-d174cb595ff0', -- Thai Massage Jam w/ Clara and Gabi @ Kedewatan
  '02398d04-c29b-4b01-abc1-618abe170d8d', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  'dcf1ccaf-e4da-4d1c-b93e-3b89ea02f1de', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  'c4d60ba7-c108-4171-a7c9-23d073cd5435', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  '3c72adf3-d994-4b82-96be-69212a741ab8', -- Dancing The Archetypes w/ Trisha @ Sayan
  'e17b54a5-778d-4d7f-95f4-6925ea8aaf8d', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  '014ced6b-12dc-4f3d-a715-cb0692b1c042', -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
  '2fc326c7-0104-4b42-9267-2e68ae105007' -- Freediving Yoga Vibration Medicine Retreat @ Outside Ubud
);

-- dup: Sunday Bhakti Kirtan with Akari Tamura (18:00:00) = Sunday Kirtan with Vasudev
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:42a1c848-70ff-4d23-9f11-dfdf1f9e5e25' WHERE status = 'approved' AND id = '1502c4d0-4f98-45a0-a42d-03553c8987f1';
-- dup: Dissolve EROS: Conscious Movement & Authentic Conn (18:00:00) = Dissolve :: Eros — Contact Improv
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:a0e92336-c32b-4827-89e9-f802bea00941' WHERE status = 'approved' AND id = '88361f34-fa63-4159-88f9-21bd3cc22c83';
-- dup: Kirtan & Cacao with Diana Beauty & Friends (18:00:00) = Sunday Kirtan with Vasudev
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:42a1c848-70ff-4d23-9f11-dfdf1f9e5e25' WHERE status = 'approved' AND id = '67d51ea0-004d-4761-a31c-1c76e2ddc086';
-- dup: Alive Ecstatic Dance: Middle Eastern Special w/ Ga (19:00:00) = Alive Ecstatic Dance: South Amercian&Shamanic Spec
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:00384f2b-72ef-4c98-b603-4f4b9e32aaab' WHERE status = 'approved' AND id = '76487cc8-5f28-4a93-bed5-853e4c83e9e6';
-- dup: Flow State Workshop (16:00:00) = Flow State Workshop w/ Samyama Self Healing Center
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:f30a2fad-d5ee-4372-bd79-070749cb5f67' WHERE status = 'approved' AND id = '42617003-f941-4633-9697-42de86c4ea9a';
-- dup: Alive Ecstatic Dance:Mantra Danza Special w/ Gabor (19:00:00) = Alive Ecstatic Dance: South Amercian&Shamanic Spec
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:00384f2b-72ef-4c98-b603-4f4b9e32aaab' WHERE status = 'approved' AND id = '665df8a6-0a58-4010-964a-8e3f1d535acd';
-- dup: Dissolve Eros w/ Tara (18:00:00) = Dissolve :: Eros — Contact Improv
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:a0e92336-c32b-4827-89e9-f802bea00941' WHERE status = 'approved' AND id = '3646ca94-e96c-4439-bf00-f83ed0476b09';
-- dup: 5Rhythms Exploration Class w/ Jada Jane (11:00:00) = 5Rhythms with Sophie
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:cfa31092-c5e8-4980-bd9f-700e30d6c76a' WHERE status = 'approved' AND id = '39f3ace1-3824-4a34-bdfa-0cc21b380819';
-- dup: 5Rhythms Moving Wave w/ Jada Jane (15:00:00) = Moving Waves — 5Rhythms with Jada Jane Boh & Sophi
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:3d0e1b0e-88fb-4b05-aed3-f2c4581fa9ae' WHERE status = 'approved' AND id = '54a2653a-7c6d-4b27-9112-c009c6f0d70f';
-- dup: Friday Ecstatic Dance w/ DION (19:15:00) = Friday Ecstatic Dance — The Yoga Barn
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:035b9866-aefb-4724-82ea-2596f8a5d789' WHERE status = 'approved' AND id = '321ed7ac-8c18-42fe-96bc-9a567872192e';
-- dup: Friday Ecstatic Dance w/ Zana Prana (19:15:00) = Friday Ecstatic Dance — The Yoga Barn
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:035b9866-aefb-4724-82ea-2596f8a5d789' WHERE status = 'approved' AND id = '825e70d7-1d36-4729-b810-f83f6d70e178';
-- dup: 5Rhythms Friday "Sweat Your Prayers®" w/ Jada Jane (11:00:00) = 5Rhythms with Sophie
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:cfa31092-c5e8-4980-bd9f-700e30d6c76a' WHERE status = 'approved' AND id = '17364e92-066f-4de9-82b2-c6a845e1d5a7';
-- dup: Friday Ecstatic Dance w/ Karunika (19:15:00) = Friday Ecstatic Dance — The Yoga Barn
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:035b9866-aefb-4724-82ea-2596f8a5d789' WHERE status = 'approved' AND id = '71cbd8f7-2472-4600-aee6-ba647e3861c9';
-- dup: Dissolve ~ Eros (18:00:00) = Dissolve :: Eros — Contact Improv
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:a0e92336-c32b-4827-89e9-f802bea00941' WHERE status = 'approved' AND id = '9c2e1f12-d9c2-4d9b-98f5-3406c228cb6d';
-- dup: Sunday Kirtan special 7 Chakras expansion sept (18:00:00) = Sunday Kirtan with Vasudev
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:42a1c848-70ff-4d23-9f11-dfdf1f9e5e25' WHERE status = 'approved' AND id = 'e49df8be-c66f-46b6-b38d-340cdf1b9808';
-- dup: Sunday Bhakti Kirtan with Vasudev (18:00:00) = Sunday Kirtan with Vasudev
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:42a1c848-70ff-4d23-9f11-dfdf1f9e5e25' WHERE status = 'approved' AND id = '7d118afb-3b51-43c1-bd60-9a96848f9fdb';
-- dup: Monday Kirtan: Live Mantra Chanting & Community Ga (19:00:00) = Monday Kirtan with Akari Tamura
UPDATE events SET status = 'archived', moderation_reason = 'duplicate_of:4101179f-0c96-4da7-9f9f-187259230621' WHERE status = 'approved' AND id = '98fe2c48-a49e-4216-83bf-d3f2c435c648';

-- 3c. Moderation still can't run: back to pending for the nightly gate (27).
UPDATE events SET status = 'pending', auto_approved_at = NULL, moderation_reason = 'walk_2026_09_27:held_unmoderated' WHERE status = 'approved' AND id IN (
  'fb7db8f6-cca1-4fb3-9efc-bb35d9b59322', -- Genius Mind Access: 40hz Gamma Cognitive Optimization @ BioSonic
  '9577d47e-3bf5-4512-aed8-d67211683eb5', -- Share What Your Ego Wants to Hide The Most ⭕ Hawimi™ Women & @ School of Unified Healing
  '2cc62c86-0ea3-4805-a5d8-8b840010c795', -- Genius Mind Access: 40hz Gamma Cognitive Optimization @ BioSonic
  '2463c119-4e18-4024-9793-303b9948fc32', -- Inner Goddess Celebration w/ Issa @ Arkamara Dijiwa
  'd13b43cd-26cf-4f63-b637-5c6d430d6dae', -- Cyanotype Workshop w/ Rizqi Akbar @ NENEK Ubud
  '27a4c1ec-388e-450f-b446-b978b82293f2', -- Vocal Activation w/ The Yogabarn @ The Yoga Barn
  'cf494de2-40c2-4951-8765-c92514fa8282', -- Dhrupad - a meditative sound journey with Dhani Gundecha @ Sayuri Healing Food Café
  '114b4859-9e86-41b0-b523-d9b90bee2b53', -- Tantric Evolution: Awaken Your Light @ Secret Tantra Temple
  '3f4564ca-38e9-4a47-b94c-110a2af46ea3', -- Tantric Evolution: Awaken Your Light @ Secret Tantra Temple
  '70727d77-da29-4039-b19e-be29b21632b5', -- The Karmic Cleanse @ The Yoga Barn
  'c8410685-e854-4753-8829-f5558cfc0ba3', -- Meridians & Acupressure for Deep Sleep @ The Yoga Barn
  '60cd2bd6-c0aa-42ee-a445-be991b2d374b', -- Journey through the Chakras: Voice & Crystal Bowl Sound Cere @ The Yoga Barn
  'd6339694-d4c2-491e-ad00-2ae376ccc818', -- Crystal & Metal Bowl Fusion @ The Yoga Barn
  '271c0fe8-0be0-4983-a9a1-8e1862a68d54', -- Ecstatic Chocolate @ The Yoga Barn
  '4990aedd-bc35-4d3f-83c2-fd81c30cc1ae', -- The Voice As Medicine: New Moon Vocal Activation & Sound Jou @ The Yoga Barn
  '1d7c4ca7-3fc0-41f7-bb46-ade39ec94232', -- VOICE, RAGA & DHRUPAD: Introduction to the Art of Indian Cla @ The Yoga Barn
  '84b14e33-4317-4fe3-9613-b8e6c092255c', -- Sound as Medicine: An Intro to Healing Sound @ The Yoga Barn
  '75086b79-aeaa-4d3e-a53a-c9bfa6d9df51', -- Blissful Sound Healing @ The Yoga Barn
  'f88f88d6-910f-421a-9c09-1c09d3512771', -- Come As You Are: A Beginning Meditation Workshop @ The Yoga Barn
  'b7c79bf6-70e2-472a-8e05-0a65ec3178d8', -- Inner Alchemy Journey @ The Yoga Barn
  'a525fcaa-6fdf-4a41-8a60-d02d989fb06f', -- Cacao, Connection and Sound Healing @ The Yoga Barn
  '111690a2-4280-489e-9693-aeffd8f2ffe8', -- Singing Together: Kirtan with Circle #69 with PREMA LOVE @ Sayuri Healing Food
  '7212d196-4ec0-43bd-8d55-85c047e8a935', -- Chakra Balancing & Sound Healing w/ Hannah @ Lumeria Yoga
  '4f0a7b8b-ecc5-4f66-865b-89e6a01877fd', -- A Night of The Beatles: 3rd The Penny Lane @ Juggan Sky
  'e0c909e0-fe79-4e54-8c46-6d522d0e9efc', -- Authenticity - The Game w/ COPA @ Zest
  '70ec609c-eaae-4aa0-86ec-63c1396738dd', -- Cacao Ceremony, Sound Journey, Medicine Song. w/ Siti Natura @ Body-Mind-Soul Bali
  '71183da0-9ac5-4cc6-bf26-0c6ccc50041e' -- Tea Ceremony @ THE BANYAN TREE
);

-- 4. Retreat testimonials: 8 quotes from "attendees" of cohorts that never ran
-- (0 bookings ever, no booking route). Unpublished, not deleted. The page no
-- longer renders them either.
UPDATE journey_testimonials SET is_published = false WHERE is_published = true;
