-- Seed "Tonight in Ubud" with recurring deals from the venues' own public pages
-- (docs/tonight/restaurants-first-30-2026-10.md, high-confidence rows only).
-- Nobody was contacted. Prices that sources disagree on are left NULL. Each row
-- lapses on its own after 30 days (expires_on default) unless reconfirmed.
INSERT INTO specials (venue_name, venue_area, venue_address, instagram_handle, website_url, title, description, price_idr, weekdays, start_time, end_time, source, source_url) VALUES
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Chicken & a free beer', 'Fried chicken with a free beer.', NULL, ARRAY[1]::smallint[], '12:00', '21:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Pasta & wine', 'Pasta with a glass of selected wine.', 135000, ARRAY[2]::smallint[], '12:00', '21:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Burger & beer', 'Burger with a beer.', 185000, ARRAY[3]::smallint[], '12:00', '21:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Steak & wine', 'Steak with a glass of wine.', 265000, ARRAY[4]::smallint[], '12:00', '21:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Pizza & beer', 'Pizza with a beer.', 170000, ARRAY[5]::smallint[], '12:00', '21:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Espetada & wine', 'Portuguese meat skewer with a glass of wine.', 225000, ARRAY[6]::smallint[], '12:00', '21:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Sunday roast', 'Beef or chicken roast. Price is from.', 190000, ARRAY[0]::smallint[], '12:00', '21:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Happy hour', 'Discounted beer, wine and cocktails.', NULL, ARRAY[1,2,3,4,5]::smallint[], '11:00', '19:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Happy hour', 'Discounted beer, wine and cocktails.', NULL, ARRAY[6,0]::smallint[], '10:00', '19:00', 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('The Blue Door', 'Ubud town', 'Jl. Monkey Forest', 'thebluedoorbali', NULL, 'Ladies'' night', 'Two cocktails and free entry to the club lounge.', NULL, ARRAY[4]::smallint[], '21:00', NULL, 'seed', 'https://thebluedoorbali.com/weekly-food-specials-in-ubud/'),
  ('No Más', 'Ubud town', 'Jl. Monkey Forest', 'nomasubud', NULL, 'Happy hour cocktails', 'Five house cocktails, plus tax.', 95000, '{}'::smallint[], '17:00', '20:00', 'seed', 'https://nomasubud.com/drink-deals'),
  ('Indus', 'Sanggingan', 'Jl. Raya Sanggingan', 'indusrestaurant', NULL, 'Two cocktails', 'Happy hour on the valley terrace, plus tax and service.', 150000, '{}'::smallint[], '16:00', '18:00', 'seed', 'https://indusbali.com/events/'),
  ('Indus', 'Sanggingan', 'Jl. Raya Sanggingan', 'indusrestaurant', NULL, 'Two-course valley lunch', 'Plus tax and service.', 195000, '{}'::smallint[], '11:00', '15:00', 'seed', 'https://indusbali.com/events/'),
  ('Cantina Rooftop', 'Sayan', 'Jl. Raya Campuhan', 'cantinarooftop.bali', NULL, 'Sundown Sundays: 2-for-1 cocktails', 'Jazz on vinyl and temple views.', NULL, ARRAY[0]::smallint[], '17:00', '18:00', 'seed', 'https://cantinarooftopbali.com/'),
  ('Folk Pool & Gardens', 'Ubud town', 'Jl. Monkey Forest', NULL, 'https://www.folkubud.com', 'Pay 1, get 2 cocktails', 'Plus tax and service.', 180000, '{}'::smallint[], '16:00', '19:00', 'seed', 'https://www.folkubud.com/offers'),
  ('Folk Pool & Gardens', 'Ubud town', 'Jl. Monkey Forest', NULL, 'https://www.folkubud.com', 'Sunday cookout', 'Poolside grill and music. Mains from IDR 85k plus tax and service.', NULL, ARRAY[0]::smallint[], '15:00', '21:00', 'seed', 'https://www.folkubud.com/offers'),
  ('Milk & Madu', 'Ubud town', 'Jl. Suweta', 'milkandmadu', NULL, '2-for-1 pizza night', 'Double the pizza, same price.', NULL, ARRAY[2,0]::smallint[], '16:00', NULL, 'seed', 'https://milkandmadu.com/'),
  ('Casa Luna', 'Ubud town', 'Jl. Raya Ubud', 'casalunabali', NULL, '2-for-1 cocktails', 'Buy one cocktail, get one free.', NULL, '{}'::smallint[], '17:00', '19:00', 'seed', 'https://casalunabali.com/'),
  ('Copper Kitchen & Rooftop', 'Ubud town', 'Jl. Bisma 68', 'copperubud', NULL, 'Pay 1, get 2 cocktails', 'Signature cocktails on the rooftop.', NULL, '{}'::smallint[], '17:00', '19:00', 'seed', 'https://www.copperubud.com/menu'),
  ('Lokal Bar', 'Ubud town', 'Jl. Monkey Forest, Gg. Beji', 'lokalbarubud', NULL, 'Free welcome arak shot', NULL, NULL, ARRAY[1,3]::smallint[], '18:00', '20:00', 'seed', 'https://lokalbarubud.com/'),
  ('Lokal Bar', 'Ubud town', 'Jl. Monkey Forest, Gg. Beji', 'lokalbarubud', NULL, 'Pay 2, get 3 cocktails', NULL, NULL, ARRAY[6]::smallint[], '15:00', '20:00', 'seed', 'https://lokalbarubud.com/'),
  ('Ibu Susu', 'Ubud town', 'Jl. Monkey Forest', 'ibu_susu_ubud', NULL, 'Happy hour cocktails', 'Plus tax and service.', 65000, '{}'::smallint[], '16:00', '19:00', 'seed', 'https://ibususu.com/'),
  ('Pinstripe', 'Petulu', 'Viceroy Bali, Jl. Lanyahan', 'pinstripebar', NULL, 'Taco Tequila Tuesday', 'Tacos with margarita specials.', NULL, ARRAY[2]::smallint[], '17:00', '21:00', 'seed', 'https://www.pinstripebar.com/blog/midweek-in-ubud/'),
  ('Pinstripe', 'Petulu', 'Viceroy Bali, Jl. Lanyahan', 'pinstripebar', NULL, 'Wine Wednesday', 'Curated wines with simple pairings.', NULL, ARRAY[3]::smallint[], '17:00', '21:00', 'seed', 'https://www.pinstripebar.com/blog/midweek-in-ubud/');
